name = "labelzoom-cloudfare"

[pages]
build_output_directory = ".next"

[build]
command = "chmod +x build.sh && ./build.sh"

[build.environment]
NODE_VERSION = "18.17.1"
NPM_VERSION = "9.6.7"

[env]
NEXT_PUBLIC_SUPABASE_URL = ""
NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = ""
CLERK_SECRET_KEY = ""
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY = ""
STRIPE_SECRET_KEY = ""
STRIPE_PRICE_ID = ""
NEXT_PUBLIC_APP_URL = "https://labelzoom.app" 